// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmppwxoxmnbvmvbslytv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcHB3eG94bW5idm12YnNseXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NTgzNTQsImV4cCI6MjA3NTIzNDM1NH0.7nwCcwgV6zFvEIHbgxq95-upGjScT0M0ZHUo2Gnj9Z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});